version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: serve -s  build -l 3000
    ports:
    - "3000:3000"
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    command: npm run start
    ports:
    - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://docker-example.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: auth
    restart: unless-stopped
    command: npm run start
    ports:
    - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

  api_db:
    image: mongo:latest
    container_name: api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth: